language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
jobs:
  include:
    - stage: Unit Tests
      script: rake
    - stage: Integration Test
      rvm: 2.5.1
      script:
         - |
           gem build kitchen-habitat.gemspec
           VERSION=$(ruby -I ./lib -e "require 'kitchen-habitat/version'; puts Kitchen::Habitat::VERSION")
           gem install kitchen-habitat-${VERSION}.gem
           kitchen test
    - stage: GitHub Release
      if: branch = master
      rvm: 2.5.1
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true